export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGINLOGIN_USER_SUCCESS_USER';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const CLEAR_ERROR_USER = 'CLEAR_ERROR_USER';
export const CLEAR_SUCCESS_USER = 'CLEAR_SUCCESS_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';

//Products
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR';
export const CURRENT_PRODUCT = 'CURRENT_PRODUCT';
export const CURRENT_PRODUCT_SUCCESS = 'CURRENT_PRODUCT_SUCCESS';
export const CURRENT_PRODUCT_ERROR = 'CURRENT_PRODUCT_ERROR';

//Cart
export const GET_CART = 'GET_CART';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_ERROR = 'GET_CART_ERROR';
export const ADD_CART = 'ADD_CART';
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS';
export const ADD_CART_ERROR = 'ADD_CART_ERROR';
export const UPDATE_CART = 'UPDATE_CART';
export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS';
export const UPDATE_CART_ERROR = 'UPDATE_CART_ERROR';
export const DELETE_QUANTITY_CART = 'DELETE_QUANTITY_CART';
export const DELETE_QUANTITY_CART_SUCCESS = 'DELETE_QUANTITY_CART_SUCCESS';
export const DELETE_QUANTITY_CART_ERROR = 'DELETE_QUANTITY_CART_ERROR';
